import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({ src: [
    {
        path: '../../public/fonts/SegoePrintRegular.woff',
        weight: '400',
        style: 'normal',
    },
    {
        path: '../../public/fonts/SegoePrintBold.ttf',
        weight: 'bold',
        style: 'normal',
    },
  ] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
